// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>crearNuevoUsuario</b><br>
 * Generated     : <b>2018/07/19 10:11:28</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 amd64 6.1 <br>
 * 
 * @since  julio 19, 2018
 * @author DELL
 */
public abstract class crearNuevoUsuarioHelper extends RationalTestScript
{
	/**
	 * Aceptar: with default state.
	 *		.class : javax.swing.plaf.basic.BasicOptionPaneUI$ButtonFactory$ConstrainedButton
	 * 		accessibleContext.accessibleName : Aceptar
	 * 		name : OptionPane.button
	 * 		.classIndex : 0
	 */
	protected GuiTestObject aceptar() 
	{
		return new GuiTestObject(
                        getMappedTestObject("aceptar"));
	}
	/**
	 * Aceptar: with specific test context and state.
	 *		.class : javax.swing.plaf.basic.BasicOptionPaneUI$ButtonFactory$ConstrainedButton
	 * 		accessibleContext.accessibleName : Aceptar
	 * 		name : OptionPane.button
	 * 		.classIndex : 0
	 */
	protected GuiTestObject aceptar(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("aceptar"), anchor, flags);
	}
	
	/**
	 * Administration: with default state.
	 *		.captionText : Administration
	 * 		.class : javax.swing.JFrame
	 * 		accessibleContext.accessibleName : Administration
	 * 		.processName : javaw.exe
	 * 		name : logFrame3
	 */
	protected TopLevelTestObject administration() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("administration"));
	}
	/**
	 * Administration: with specific test context and state.
	 *		.captionText : Administration
	 * 		.class : javax.swing.JFrame
	 * 		accessibleContext.accessibleName : Administration
	 * 		.processName : javaw.exe
	 * 		name : logFrame3
	 */
	protected TopLevelTestObject administration(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("administration"), anchor, flags);
	}
	
	/**
	 * Album: with default state.
	 *		tabCount : 2
	 * 		.class : javax.swing.JTabbedPane
	 * 		accessibleContext.accessibleName : Album
	 * 		.tabs : {Album,Details}
	 * 		name : tabbedPane
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject album() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("album"));
	}
	/**
	 * Album: with specific test context and state.
	 *		tabCount : 2
	 * 		.class : javax.swing.JTabbedPane
	 * 		accessibleContext.accessibleName : Album
	 * 		.tabs : {Album,Details}
	 * 		name : tabbedPane
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject album(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("album"), anchor, flags);
	}
	
	/**
	 * BannerJpg: with default state.
	 *		.class : javax.swing.JLabel
	 * 		iconDescription : Banner.jpg
	 * 		.classIndex : 1
	 */
	protected GuiTestObject bannerJpg() 
	{
		return new GuiTestObject(
                        getMappedTestObject("bannerJpg"));
	}
	/**
	 * BannerJpg: with specific test context and state.
	 *		.class : javax.swing.JLabel
	 * 		iconDescription : Banner.jpg
	 * 		.classIndex : 1
	 */
	protected GuiTestObject bannerJpg(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("bannerJpg"), anchor, flags);
	}
	
	/**
	 * Close: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Close
	 * 		name : close2
	 * 		.classIndex : 1
	 */
	protected GuiTestObject close() 
	{
		return new GuiTestObject(
                        getMappedTestObject("close"));
	}
	/**
	 * Close: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Close
	 * 		name : close2
	 * 		.classIndex : 1
	 */
	protected GuiTestObject close(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("close"), anchor, flags);
	}
	
	/**
	 * Close: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Close
	 * 		name : close
	 * 		.classIndex : 1
	 */
	protected GuiTestObject close2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("close2"));
	}
	/**
	 * Close: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Close
	 * 		name : close
	 * 		.classIndex : 1
	 */
	protected GuiTestObject close2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("close2"), anchor, flags);
	}
	
	/**
	 * custTable: with default state.
	 *		.class : javax.swing.JTable
	 * 		name : custTable
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject custTable() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("custTable"));
	}
	/**
	 * custTable: with specific test context and state.
	 *		.class : javax.swing.JTable
	 * 		name : custTable
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject custTable(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("custTable"), anchor, flags);
	}
	
	/**
	 * DeleteSelectedCustomer: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Delete Selected Customer
	 * 		name : deleteCustomer
	 * 		.classIndex : 0
	 */
	protected GuiTestObject deleteSelectedCustomer() 
	{
		return new GuiTestObject(
                        getMappedTestObject("deleteSelectedCustomer"));
	}
	/**
	 * DeleteSelectedCustomer: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Delete Selected Customer
	 * 		name : deleteCustomer
	 * 		.classIndex : 0
	 */
	protected GuiTestObject deleteSelectedCustomer(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("deleteSelectedCustomer"), anchor, flags);
	}
	
	/**
	 * DeleteSelectedOrder: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Delete Selected Order
	 * 		name : deleteOrder
	 * 		.classIndex : 0
	 */
	protected GuiTestObject deleteSelectedOrder() 
	{
		return new GuiTestObject(
                        getMappedTestObject("deleteSelectedOrder"));
	}
	/**
	 * DeleteSelectedOrder: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Delete Selected Order
	 * 		name : deleteOrder
	 * 		.classIndex : 0
	 */
	protected GuiTestObject deleteSelectedOrder(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("deleteSelectedOrder"), anchor, flags);
	}
	
	/**
	 * jmb: with default state.
	 *		.class : javax.swing.JMenuBar
	 * 		name : jmb
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject jmb() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("jmb"));
	}
	/**
	 * jmb: with specific test context and state.
	 *		.class : javax.swing.JMenuBar
	 * 		name : jmb
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject jmb(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("jmb"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : OK
	 * 		name : but
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok() 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : OK
	 * 		name : but
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName :   OK  
	 * 		name : ok
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok2"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName :   OK  
	 * 		name : ok
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok2"), anchor, flags);
	}
	
	/**
	 * orderTable: with default state.
	 *		.class : javax.swing.JTable
	 * 		name : orderTable
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject orderTable() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("orderTable"));
	}
	/**
	 * orderTable: with specific test context and state.
	 *		.class : javax.swing.JTable
	 * 		name : orderTable
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject orderTable(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("orderTable"), anchor, flags);
	}
	
	/**
	 * YES: with default state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel : Are you sure you want to clear all customers and orders?  (Products info will no ...
	 * 		accessibleContext.accessibleName : YES
	 * 		name : ok-yes
	 * 		.classIndex : 0
	 */
	protected GuiTestObject yes() 
	{
		return new GuiTestObject(
                        getMappedTestObject("yes"));
	}
	/**
	 * YES: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel : Are you sure you want to clear all customers and orders?  (Products info will no ...
	 * 		accessibleContext.accessibleName : YES
	 * 		name : ok-yes
	 * 		.classIndex : 0
	 */
	protected GuiTestObject yes(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("yes"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point BannerJpg_BannerJpg object in the SUT.
	 */
	protected IFtVerificationPoint BannerJpg_BannerJpgVP() 
	{
		return vp("BannerJpg_BannerJpg");
	}
	protected IFtVerificationPoint BannerJpg_BannerJpgVP(TestObject anchor)
	{
		return vp("BannerJpg_BannerJpg", anchor);
	}
	
	

	protected crearNuevoUsuarioHelper()
	{
		setScriptName("crearNuevoUsuario");
	}
	
}

