// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>validateStars</b><br>
 * Generated     : <b>2018/07/19 10:26:46</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 amd64 6.1 <br>
 * 
 * @since  julio 19, 2018
 * @author DELL
 */
public abstract class validateStarsHelper extends RationalTestScript
{
	/**
	 * nameCombo: with default state.
	 *		.itemCount : 16
	 * 		.itemText : {Trent Culpito,Susan Flontly,Emma Trenchenza,Claire Stratus,Rick Tumbler,Tony Mi ...
	 * 		.class : javax.swing.JComboBox
	 * 		.priorLabel : Full Name:
	 * 		name : nameCombo
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject nameCombo() 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("nameCombo"));
	}
	/**
	 * nameCombo: with specific test context and state.
	 *		.itemCount : 16
	 * 		.itemText : {Trent Culpito,Susan Flontly,Emma Trenchenza,Claire Stratus,Rick Tumbler,Tony Mi ...
	 * 		.class : javax.swing.JComboBox
	 * 		.priorLabel : Full Name:
	 * 		name : nameCombo
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject nameCombo(TestObject anchor, long flags) 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("nameCombo"), anchor, flags);
	}
	
	/**
	 * PlaceOrder: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Place Order
	 * 		name : placeOrderButton2
	 * 		.classIndex : 0
	 */
	protected GuiTestObject placeOrder() 
	{
		return new GuiTestObject(
                        getMappedTestObject("placeOrder"));
	}
	/**
	 * PlaceOrder: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Place Order
	 * 		name : placeOrderButton2
	 * 		.classIndex : 0
	 */
	protected GuiTestObject placeOrder(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("placeOrder"), anchor, flags);
	}
	
	

	protected validateStarsHelper()
	{
		setScriptName("validateStars");
	}
	
}

