// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>validateOrderElimitaion</b><br>
 * Generated     : <b>2018/07/19 10:31:41</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 amd64 6.1 <br>
 * 
 * @since  julio 19, 2018
 * @author DELL
 */
public abstract class validateOrderElimitaionHelper extends RationalTestScript
{
	/**
	 * ClassicsCD: with default state.
	 *		.captionText : ClassicsCD
	 * 		.class : ClassicsJava
	 * 		accessibleContext.accessibleName : ClassicsCD
	 * 		.processName : javaw.exe
	 */
	protected TopLevelTestObject classicsCD() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("classicsCD"));
	}
	/**
	 * ClassicsCD: with specific test context and state.
	 *		.captionText : ClassicsCD
	 * 		.class : ClassicsJava
	 * 		accessibleContext.accessibleName : ClassicsCD
	 * 		.processName : javaw.exe
	 */
	protected TopLevelTestObject classicsCD(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("classicsCD"), anchor, flags);
	}
	
	/**
	 * Close: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Close
	 * 		name : close2
	 * 		.classIndex : 1
	 */
	protected GuiTestObject close() 
	{
		return new GuiTestObject(
                        getMappedTestObject("close"));
	}
	/**
	 * Close: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Close
	 * 		name : close2
	 * 		.classIndex : 1
	 */
	protected GuiTestObject close(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("close"), anchor, flags);
	}
	
	/**
	 * DeleteSelectedOrder: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Delete Selected Order
	 * 		name : deleteOrder
	 * 		.classIndex : 0
	 */
	protected GuiTestObject deleteSelectedOrder() 
	{
		return new GuiTestObject(
                        getMappedTestObject("deleteSelectedOrder"));
	}
	/**
	 * DeleteSelectedOrder: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Delete Selected Order
	 * 		name : deleteOrder
	 * 		.classIndex : 0
	 */
	protected GuiTestObject deleteSelectedOrder(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("deleteSelectedOrder"), anchor, flags);
	}
	
	/**
	 * jmb: with default state.
	 *		.class : javax.swing.JMenuBar
	 * 		name : jmb
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject jmb() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("jmb"));
	}
	/**
	 * jmb: with specific test context and state.
	 *		.class : javax.swing.JMenuBar
	 * 		name : jmb
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject jmb(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("jmb"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName :   OK  
	 * 		name : ok
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok() 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName :   OK  
	 * 		name : ok
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok"), anchor, flags);
	}
	
	/**
	 * orderTable: with default state.
	 *		.class : javax.swing.JTable
	 * 		name : orderTable
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject orderTable() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("orderTable"));
	}
	/**
	 * orderTable: with specific test context and state.
	 *		.class : javax.swing.JTable
	 * 		name : orderTable
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject orderTable(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("orderTable"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point orderTable_standard object in the SUT.
	 */
	protected IFtVerificationPoint orderTable_standardVP() 
	{
		return vp("orderTable_standard");
	}
	protected IFtVerificationPoint orderTable_standardVP(TestObject anchor)
	{
		return vp("orderTable_standard", anchor);
	}
	
	/**
	 * Locate and return the verification point orderTable_standard_2 object in the SUT.
	 */
	protected IFtVerificationPoint orderTable_standard_2VP() 
	{
		return vp("orderTable_standard_2");
	}
	protected IFtVerificationPoint orderTable_standard_2VP(TestObject anchor)
	{
		return vp("orderTable_standard_2", anchor);
	}
	
	

	protected validateOrderElimitaionHelper()
	{
		setScriptName("validateOrderElimitaion");
	}
	
}

